BarcodeKit: UPCE Class Reference
UPCE Class Reference
#include <UPCE.h>
Inherits IGuardPatterns.
Public Member Functions
UPCE (string *data)
~UPCE ()
void encodeSymbol (const string *data)
void encodeQuietZones ()
void encodeGuardPatterns ()
void setGuardPatterns (string left, string centre, string right)
vector< string > getGuardPatterns ()
vector< int > * stringToVector (string aString)
bool verifyContent (const string *content)
string * zeroSuppression (const string *data)
bool isZeroSuppresible (const string *data)
int getZSPattern ()
void setZSPattern (int pattern)
Public Attributes
string filename
string checkFilename
vector< string > guardPatterns
xml_document< > parsed_xml
xml_document< > parity_xml
int zsPattern
Detailed Description
Definition at line 23 of file UPCE.h.
Constructor & Destructor Documentation
UPCE::UPCE (string * data)
Definition at line 28 of file UPCE.cpp.
References checkFilename, encodeQuietZones(), filename, getXMLToParse(), parity_xml, parsed_xml, and setGuardPatterns().
UPCE::~UPCE ()
Definition at line 59 of file UPCE.cpp.
Member Function Documentation
void UPCE::encodeGuardPatterns () [virtual]
Implements IGuardPatterns.
Definition at line 286 of file UPCE.cpp.
References BaseBarcode::addEncodedSymbol(), createSymbol(), getGuardPatterns(), and stringToVector().
Referenced by encodeSymbol().
void UPCE::encodeQuietZones ()
Definition at line 267 of file UPCE.cpp.
References BaseBarcode::addEncodedSymbol(), createSymbol(), and parsed_xml.
Referenced by UPCE().
void UPCE::encodeSymbol (const string * data)
Definition at line 231 of file UPCE.cpp.
References BaseBarcode::addEncodedSymbol(), createSymbol(), encodeGuardPatterns(), kASCII, parity_xml, parsed_xml, stringToVector(), and zeroSuppression().
vector< string > UPCE::getGuardPatterns () [virtual]
Implements IGuardPatterns.
Definition at line 317 of file UPCE.cpp.
References guardPatterns.
Referenced by encodeGuardPatterns().
int UPCE::getZSPattern ()
Definition at line 175 of file UPCE.cpp.
References zsPattern.
Referenced by zeroSuppression().
bool UPCE::isZeroSuppresible (const string * data)
Definition at line 147 of file UPCE.cpp.
References kPatternA, kPatternB, kPatternC, kPatternD, setZSPattern(), and stringToVector().
Referenced by verifyContent().
void UPCE::setGuardPatterns (string left, string centre, string right) [virtual]
Implements IGuardPatterns.
Definition at line 310 of file UPCE.cpp.
References guardPatterns.
Referenced by UPCE().
void UPCE::setZSPattern (int pattern)
Definition at line 182 of file UPCE.cpp.
References zsPattern.
Referenced by isZeroSuppresible().
vector< int > * UPCE::stringToVector (string aString)
Definition at line 323 of file UPCE.cpp.
Referenced by encodeGuardPatterns(), encodeSymbol(), and isZeroSuppresible().
bool UPCE::verifyContent (const string * content)
Definition at line 65 of file UPCE.cpp.
References isZeroSuppresible().
string * UPCE::zeroSuppression (const string * data)
Definition at line 102 of file UPCE.cpp.
References getZSPattern(), kPatternA, kPatternB, kPatternC, and kPatternD.
Referenced by encodeSymbol().
Member Data Documentation
string UPCE::checkFilename
Definition at line 45 of file UPCE.h.
Referenced by UPCE().
string UPCE::filename
Definition at line 44 of file UPCE.h.
Referenced by UPCE().
vector< string > UPCE::guardPatterns
Definition at line 46 of file UPCE.h.
Referenced by getGuardPatterns(), and setGuardPatterns().
xml_document< > UPCE::parity_xml
Definition at line 48 of file UPCE.h.
Referenced by encodeSymbol(), and UPCE().
xml_document< > UPCE::parsed_xml
Definition at line 47 of file UPCE.h.
Referenced by encodeQuietZones(), encodeSymbol(), and UPCE().
int UPCE::zsPattern
Definition at line 49 of file UPCE.h.
Referenced by getZSPattern(), and setZSPattern().
The documentation for this class was generated from the following files:
/Dropbox/MSc Course/Final Project/BarcodeKit/BarcodeKit/UPCE.h
/Dropbox/MSc Course/Final Project/BarcodeKit/BarcodeKit/UPCE.cpp