BarcodeKit: Interleaved2of5 Class Reference
Interleaved2of5 Class Reference
#include <Interleaved2of5.h>
Inherits BaseBarcode.
Public Member Functions
Interleaved2of5 (string *data)
~Interleaved2of5 ()
bool verifyContent (const string *content)
void encodeCheckCharacter (const string *data)
void encodeSymbol (const string *data)
void encodeStartStop ()
void encodeQuietZones ()
Private Member Functions
vector< int > * stringToVector (string aString)
Private Attributes
string filename
xml_document< > parsed_xml
Detailed Description
Definition at line 22 of file Interleaved2of5.h.
Constructor & Destructor Documentation
Interleaved2of5::Interleaved2of5 (string * data)
Definition at line 26 of file Interleaved2of5.cpp.
References encodeCheckCharacter(), encodeQuietZones(), encodeStartStop(), filename, BaseBarcode::getXMLToParse(), kModulus, parsed_xml, BaseBarcode::setCheckcharModulus(), BaseBarcode::setDataLength(), and BaseBarcode::verifyData().
Interleaved2of5::~Interleaved2of5 ()
Definition at line 48 of file Interleaved2of5.cpp.
Member Function Documentation
void Interleaved2of5::encodeCheckCharacter (const string * data) [virtual]
Implements BaseBarcode.
Definition at line 150 of file Interleaved2of5.cpp.
References BaseBarcode::completedDataString, encodeSymbol(), and kModulus.
Referenced by Interleaved2of5().
void Interleaved2of5::encodeQuietZones () [virtual]
Implements BaseBarcode.
Definition at line 135 of file Interleaved2of5.cpp.
References BaseBarcode::addEncodedSymbol(), BaseBarcode::createSymbol(), BaseBarcode::encodedSymbols, and parsed_xml.
Referenced by Interleaved2of5().
void Interleaved2of5::encodeStartStop () [virtual]
Implements BaseBarcode.
Definition at line 117 of file Interleaved2of5.cpp.
References BaseBarcode::addEncodedSymbol(), BaseBarcode::createSymbol(), BaseBarcode::encodedSymbols, parsed_xml, and stringToVector().
Referenced by Interleaved2of5().
void Interleaved2of5::encodeSymbol (const string * data) [virtual]
Implements BaseBarcode.
Definition at line 74 of file Interleaved2of5.cpp.
References BaseBarcode::addEncodedSymbol(), BaseBarcode::createSymbol(), kASCII, parsed_xml, and stringToVector().
Referenced by encodeCheckCharacter().
vector< int > * Interleaved2of5::stringToVector (string aString) [private]
Definition at line 188 of file Interleaved2of5.cpp.
Referenced by encodeStartStop(), and encodeSymbol().
bool Interleaved2of5::verifyContent (const string * content) [virtual]
Implements BaseBarcode.
Definition at line 53 of file Interleaved2of5.cpp.
Member Data Documentation
string Interleaved2of5::filename [private]
Definition at line 35 of file Interleaved2of5.h.
Referenced by Interleaved2of5().
xml_document< > Interleaved2of5::parsed_xml [private]
Definition at line 36 of file Interleaved2of5.h.
Referenced by encodeQuietZones(), encodeStartStop(), encodeSymbol(), and Interleaved2of5().
The documentation for this class was generated from the following files:
/Dropbox/MSc Course/Final Project/BarcodeKit/BarcodeKit/Interleaved2of5.h
/Dropbox/MSc Course/Final Project/BarcodeKit/BarcodeKit/Interleaved2of5.cpp