BarcodeKit: UPCA Class Reference
UPCA Class Reference
#include <UPCA.h>
Inherits IGuardPatterns.
Public Member Functions
UPCA (string *data)
~UPCA ()
void encodeSymbol (const string *data)
void encodeQuietZones ()
void encodeGuardPatterns ()
void setGuardPatterns (string left, string centre, string right)
vector< string > getGuardPatterns ()
vector< int > * stringToVector (string aString)
Public Attributes
string filename
string parityFilename
vector< string > guardPatterns
xml_document< > parsed_xml
Detailed Description
Definition at line 23 of file UPCA.h.
Constructor & Destructor Documentation
UPCA::UPCA (string * data)
Definition at line 24 of file UPCA.cpp.
References encodeQuietZones(), filename, getXMLToParse(), parsed_xml, and setGuardPatterns().
UPCA::~UPCA ()
Definition at line 53 of file UPCA.cpp.
Member Function Documentation
void UPCA::encodeGuardPatterns () [virtual]
Implements IGuardPatterns.
Definition at line 124 of file UPCA.cpp.
References BaseBarcode::addEncodedSymbol(), createSymbol(), getGuardPatterns(), and stringToVector().
Referenced by encodeSymbol().
void UPCA::encodeQuietZones ()
Definition at line 105 of file UPCA.cpp.
References BaseBarcode::addEncodedSymbol(), createSymbol(), and parsed_xml.
Referenced by UPCA().
void UPCA::encodeSymbol (const string * data)
Definition at line 59 of file UPCA.cpp.
References BaseBarcode::addEncodedSymbol(), createSymbol(), encodeGuardPatterns(), kASCII, parsed_xml, and stringToVector().
vector< string > UPCA::getGuardPatterns () [virtual]
Implements IGuardPatterns.
Definition at line 160 of file UPCA.cpp.
References guardPatterns.
Referenced by encodeGuardPatterns().
void UPCA::setGuardPatterns (string left, string centre, string right) [virtual]
Implements IGuardPatterns.
Definition at line 152 of file UPCA.cpp.
References guardPatterns.
Referenced by UPCA().
vector< int > * UPCA::stringToVector (string aString)
Definition at line 166 of file UPCA.cpp.
Referenced by encodeGuardPatterns(), and encodeSymbol().
Member Data Documentation
string UPCA::filename
Definition at line 35 of file UPCA.h.
Referenced by UPCA().
vector< string > UPCA::guardPatterns
Definition at line 37 of file UPCA.h.
Referenced by getGuardPatterns(), and setGuardPatterns().
string UPCA::parityFilename
Definition at line 36 of file UPCA.h.
xml_document< > UPCA::parsed_xml
Definition at line 38 of file UPCA.h.
Referenced by encodeQuietZones(), encodeSymbol(), and UPCA().
The documentation for this class was generated from the following files:
/Dropbox/MSc Course/Final Project/BarcodeKit/BarcodeKit/UPCA.h
/Dropbox/MSc Course/Final Project/BarcodeKit/BarcodeKit/UPCA.cpp