BarcodeKit: Symbol Class Reference
Symbol Class Reference
#include <Symbol.h>
Public Member Functions
Symbol ()
Symbol (int characterData[], int dataLength)
Symbol (int characterData[], int dataLength, int startWith)
Symbol (int characterData[], int dataLength, int startWith, int gapWidth)
Symbol (int characterData[], int dataLength, int startWith, int gapWidth, int ofType)
~Symbol ()
int getLeadingElement ()
int getIntercharGap ()
int getSymbolType ()
vector< int > * getEncodedData ()
int getForcePostion ()
int getAsciiEquivalent ()
string getTextEquivalent ()
void setLeadingElement (int le)
void setIntercharGap (int icg)
void setSymbolType (int st)
void setEncodedData (vector< int > const &ec)
void setForcedPosition (int fp)
void setAsciiEquivalent (int ae)
void setTextEquivalent (string &te)
Private Member Functions
void arrayIntoVector (int source[], int sourceLength, vector< int > &destination)
Private Attributes
int leadingElement
int intercharacterGap
int symbolType
vector< int > encodedSymbol
int forcePosition
int asciiEquivalent
string textEquivalent
Detailed Description
Definition at line 18 of file Symbol.h.
Constructor & Destructor Documentation
Symbol::Symbol ()
Definition at line 18 of file Symbol.cpp.
Symbol::Symbol (int characterData[], int dataLength)
Definition at line 23 of file Symbol.cpp.
References arrayIntoVector(), and encodedSymbol.
Symbol::Symbol (int characterData[], int dataLength, int startWith)
Definition at line 28 of file Symbol.cpp.
References arrayIntoVector(), encodedSymbol, and leadingElement.
Symbol::Symbol (int characterData[], int dataLength, int startWith, int gapWidth)
Definition at line 34 of file Symbol.cpp.
References arrayIntoVector(), encodedSymbol, intercharacterGap, and leadingElement.
Symbol::Symbol (int characterData[], int dataLength, int startWith, int gapWidth, int ofType)
Definition at line 41 of file Symbol.cpp.
References arrayIntoVector(), encodedSymbol, intercharacterGap, leadingElement, and symbolType.
Symbol::~Symbol ()
Definition at line 49 of file Symbol.cpp.
Member Function Documentation
void Symbol::arrayIntoVector (int source[], int sourceLength, vector< int > & destination) [private]
Definition at line 132 of file Symbol.cpp.
Referenced by Symbol().
int Symbol::getAsciiEquivalent ()
Definition at line 84 of file Symbol.cpp.
References asciiEquivalent.
vector< int > * Symbol::getEncodedData ()
Definition at line 72 of file Symbol.cpp.
References encodedSymbol.
Referenced by testSymbol().
int Symbol::getForcePostion ()
Definition at line 79 of file Symbol.cpp.
References forcePosition.
Referenced by testSymbol().
int Symbol::getIntercharGap ()
Definition at line 62 of file Symbol.cpp.
References intercharacterGap.
Referenced by testSymbol().
int Symbol::getLeadingElement ()
Definition at line 57 of file Symbol.cpp.
References leadingElement.
Referenced by testSymbol().
int Symbol::getSymbolType ()
Definition at line 67 of file Symbol.cpp.
References symbolType.
Referenced by testSymbol().
string Symbol::getTextEquivalent ()
Definition at line 89 of file Symbol.cpp.
References textEquivalent.
void Symbol::setAsciiEquivalent (int ae)
Definition at line 119 of file Symbol.cpp.
References asciiEquivalent.
void Symbol::setEncodedData (vector< int > const & ec)
Definition at line 109 of file Symbol.cpp.
References encodedSymbol.
Referenced by createSymbol(), and BaseBarcode::createSymbol().
void Symbol::setForcedPosition (int fp)
Definition at line 114 of file Symbol.cpp.
References forcePosition.
Referenced by createSymbol(), and BaseBarcode::createSymbol().
void Symbol::setIntercharGap (int icg)
Definition at line 99 of file Symbol.cpp.
References intercharacterGap.
Referenced by createSymbol(), and BaseBarcode::createSymbol().
void Symbol::setLeadingElement (int le)
Definition at line 94 of file Symbol.cpp.
References leadingElement.
Referenced by createSymbol(), and BaseBarcode::createSymbol().
void Symbol::setSymbolType (int st)
Definition at line 104 of file Symbol.cpp.
References symbolType.
Referenced by createSymbol(), and BaseBarcode::createSymbol().
void Symbol::setTextEquivalent (string & te)
Definition at line 124 of file Symbol.cpp.
References textEquivalent.
Member Data Documentation
int Symbol::asciiEquivalent [private]
Definition at line 54 of file Symbol.h.
Referenced by getAsciiEquivalent(), and setAsciiEquivalent().
vector<int> Symbol::encodedSymbol [private]
Definition at line 52 of file Symbol.h.
Referenced by getEncodedData(), setEncodedData(), and Symbol().
int Symbol::forcePosition [private]
Definition at line 53 of file Symbol.h.
Referenced by getForcePostion(), and setForcedPosition().
int Symbol::intercharacterGap [private]
Definition at line 50 of file Symbol.h.
Referenced by getIntercharGap(), setIntercharGap(), and Symbol().
int Symbol::leadingElement [private]
Definition at line 49 of file Symbol.h.
Referenced by getLeadingElement(), setLeadingElement(), and Symbol().
int Symbol::symbolType [private]
Definition at line 51 of file Symbol.h.
Referenced by getSymbolType(), setSymbolType(), and Symbol().
string Symbol::textEquivalent [private]
Definition at line 55 of file Symbol.h.
Referenced by getTextEquivalent(), and setTextEquivalent().
The documentation for this class was generated from the following files:
/Dropbox/MSc Course/Final Project/BarcodeKit/BarcodeKit/Symbol.h
/Dropbox/MSc Course/Final Project/BarcodeKit/BarcodeKit/Symbol.cpp