BarcodeKit: BaseEANUPC Class Reference
BaseEANUPC Class Reference
#include <BaseEANUPC.h>
Inherits BaseBarcode, and IGuardPatterns.
Inherited by EAN13, and EAN8.
Public Member Functions
BaseEANUPC ()
~BaseEANUPC ()
bool verifyContent (const string *content)
virtual void encodeSymbol (const string *data)
virtual void encodeQuietZones ()
virtual void encodeStartStop ()
virtual void encodeCheckCharacter (const string *data)
virtual void setGuardPatterns (string left, string centre, string right)=0
virtual vector< string > getGuardPatterns ()=0
virtual void encodeGuardPatterns ()=0
Detailed Description
Definition at line 22 of file BaseEANUPC.h.
Constructor & Destructor Documentation
BaseEANUPC::BaseEANUPC ()
Definition at line 22 of file BaseEANUPC.cpp.
References BaseBarcode::setCheckcharModulus().
BaseEANUPC::~BaseEANUPC ()
Definition at line 27 of file BaseEANUPC.cpp.
Member Function Documentation
void BaseEANUPC::encodeCheckCharacter (const string * data) [virtual]
Implements BaseBarcode.
Definition at line 69 of file BaseEANUPC.cpp.
References BaseBarcode::completedDataString, and encodeSymbol().
Referenced by EAN13::EAN13(), and EAN8::EAN8().
virtual void BaseEANUPC::encodeGuardPatterns () [pure virtual]
Implements IGuardPatterns.
Implemented in EAN13, and EAN8.
void BaseEANUPC::encodeQuietZones () [virtual]
Implements BaseBarcode.
Reimplemented in EAN13, and EAN8.
Definition at line 59 of file BaseEANUPC.cpp.
void BaseEANUPC::encodeStartStop () [virtual]
Implements BaseBarcode.
Definition at line 64 of file BaseEANUPC.cpp.
void BaseEANUPC::encodeSymbol (const string * data) [virtual]
Implements BaseBarcode.
Reimplemented in EAN13, and EAN8.
Definition at line 54 of file BaseEANUPC.cpp.
Referenced by encodeCheckCharacter().
virtual vector< string > BaseEANUPC::getGuardPatterns () [pure virtual]
Implements IGuardPatterns.
Implemented in EAN13, and EAN8.
virtual void BaseEANUPC::setGuardPatterns (string left, string centre, string right) [pure virtual]
Implements IGuardPatterns.
Implemented in EAN13, and EAN8.
bool BaseEANUPC::verifyContent (const string * content) [virtual]
Implements BaseBarcode.
Definition at line 32 of file BaseEANUPC.cpp.
The documentation for this class was generated from the following files:
/Dropbox/MSc Course/Final Project/BarcodeKit/BarcodeKit/BaseEANUPC.h
/Dropbox/MSc Course/Final Project/BarcodeKit/BarcodeKit/BaseEANUPC.cpp