BarcodeKit: Code128 Class Reference
Code128 Class Reference
#include <Code128.h>
Inherits Base128.
Public Member Functions
Code128 (string *data)
~Code128 ()
int getSet (char first)
bool verifyContent (const string *content)
void encodeStartStop ()
void encodeQuietZones ()
void encodeCheckCharacter (const string *data)
int returnCheckCharASCII ()
Private Member Functions
vector< int > * stringToVector (string aString)
Private Attributes
string filename
xml_document< > parsed_xml
Detailed Description
Definition at line 22 of file Code128.h.
Constructor & Destructor Documentation
Code128::Code128 (string * data)
Definition at line 30 of file Code128.cpp.
References BaseBarcode::addEncodedSymbol(), Base128::checkCharList, BaseBarcode::createSymbol(), encodeCheckCharacter(), encodeQuietZones(), encodeStartStop(), Base128::encodeSymbol(), filename, getSet(), BaseBarcode::getXMLToParse(), kModulus, kSetA, kSetB, kSetC, parsed_xml, BaseBarcode::setCheckcharModulus(), BaseBarcode::setDataLength(), stringToVector(), and BaseBarcode::verifyData().
Code128::~Code128 ()
Definition at line 83 of file Code128.cpp.
References Base128::checkCharList.
Member Function Documentation
void Code128::encodeCheckCharacter (const string * data) [virtual]
Implements BaseBarcode.
Definition at line 154 of file Code128.cpp.
References BaseBarcode::addEncodedSymbol(), Base128::checkCharList, BaseBarcode::createSymbol(), BaseBarcode::encodedSymbols, kASCII, parsed_xml, and stringToVector().
Referenced by Code128().
void Code128::encodeQuietZones () [virtual]
Implements BaseBarcode.
Definition at line 138 of file Code128.cpp.
References BaseBarcode::addEncodedSymbol(), BaseBarcode::createSymbol(), BaseBarcode::encodedSymbols, and parsed_xml.
Referenced by Code128().
void Code128::encodeStartStop () [virtual]
Implements BaseBarcode.
Definition at line 130 of file Code128.cpp.
References BaseBarcode::addEncodedSymbol(), BaseBarcode::createSymbol(), BaseBarcode::encodedSymbols, kStop, and stringToVector().
Referenced by Code128().
int Code128::getSet (char first)
Definition at line 90 of file Code128.cpp.
References kASCII, kSetA, kSetB, kSetC, and parsed_xml.
Referenced by Code128().
int Code128::returnCheckCharASCII () [virtual]
Implements Base128.
Definition at line 191 of file Code128.cpp.
vector< int > * Code128::stringToVector (string aString) [private]
Definition at line 197 of file Code128.cpp.
Referenced by Code128(), encodeCheckCharacter(), and encodeStartStop().
bool Code128::verifyContent (const string * content) [virtual]
Implements BaseBarcode.
Definition at line 115 of file Code128.cpp.
Member Data Documentation
string Code128::filename [private]
Definition at line 35 of file Code128.h.
Referenced by Code128().
xml_document< > Code128::parsed_xml [private]
Definition at line 36 of file Code128.h.
Referenced by Code128(), encodeCheckCharacter(), encodeQuietZones(), and getSet().
The documentation for this class was generated from the following files:
/Dropbox/MSc Course/Final Project/BarcodeKit/BarcodeKit/Code128.h
/Dropbox/MSc Course/Final Project/BarcodeKit/BarcodeKit/Code128.cpp