BarcodeKit: BaseBarcode Class Reference
BaseBarcode Class Reference
#include <BaseBarcode.h>
Inherited by Base128, BaseEANUPC, Codabar, Code39, and Interleaved2of5.
Public Member Functions
vector< int > getQuietzoneWidths ()
deque< Symbol * > getEncodedSymbols ()
int getCheckcharModulus ()
int getDataLength ()
Protected Member Functions
BaseBarcode ()
~BaseBarcode ()
void setQuietzoneWidths (int left, int right, int upper, int lower)
void addEncodedSymbol (Symbol *symbol)
void addEncodedSymbol (Symbol *symbol, int position)
void setCheckcharModulus (int modulus)
void setDataLength (int length)
virtual bool verifyData (const string *data)
virtual bool verifyLength (const int length)
virtual bool verifyContent (const string *content)=0
virtual void encodeSymbol (const string *data)=0
virtual void encodeStartStop ()=0
virtual void encodeQuietZones ()=0
virtual void encodeCheckCharacter (const string *data)=0
Symbol * createSymbol (int st, int ic, int le, int fp, vector< int > *aVector)
char * getXMLToParse (string *fileTitle)
vector< string > returnDOMValues (rapidxml::xml_node< > *node)
Protected Attributes
vector< int > quietzoneWidths
deque< Symbol * > encodedSymbols
int checkcharModulus
int dataLength
string completedDataString
Detailed Description
Definition at line 20 of file BaseBarcode.h.
Constructor & Destructor Documentation
BaseBarcode::BaseBarcode () [protected]
Definition at line 21 of file BaseBarcode.cpp.
BaseBarcode::~BaseBarcode () [protected]
Definition at line 26 of file BaseBarcode.cpp.
Member Function Documentation
void BaseBarcode::addEncodedSymbol (Symbol * symbol, int position) [protected]
Definition at line 78 of file BaseBarcode.cpp.
References encodedSymbols.
void BaseBarcode::addEncodedSymbol (Symbol * symbol) [protected]
Definition at line 72 of file BaseBarcode.cpp.
References encodedSymbols.
Referenced by Code128::Code128(), Code39::encodeCheckCharacter(), Code128::encodeCheckCharacter(), UPCE::encodeGuardPatterns(), UPCA::encodeGuardPatterns(), EAN8::encodeGuardPatterns(), EAN13::encodeGuardPatterns(), UPCE::encodeQuietZones(), UPCA::encodeQuietZones(), Interleaved2of5::encodeQuietZones(), EAN8::encodeQuietZones(), EAN13::encodeQuietZones(), Code39::encodeQuietZones(), Code128::encodeQuietZones(), Codabar::encodeQuietZones(), Interleaved2of5::encodeStartStop(), Code39::encodeStartStop(), Code128::encodeStartStop(), Codabar::encodeStartStop(), UPCE::encodeSymbol(), UPCA::encodeSymbol(), Interleaved2of5::encodeSymbol(), EAN8::encodeSymbol(), EAN13::encodeSymbol(), Code39::encodeSymbol(), Codabar::encodeSymbol(), and Base128::encodeSymbol().
Symbol * BaseBarcode::createSymbol (int st, int ic, int le, int fp, vector< int > * aVector) [protected]
Definition at line 132 of file BaseBarcode.cpp.
References Symbol::setEncodedData(), Symbol::setForcedPosition(), Symbol::setIntercharGap(), Symbol::setLeadingElement(), and Symbol::setSymbolType().
Referenced by Code128::Code128(), Code39::encodeCheckCharacter(), Code128::encodeCheckCharacter(), EAN8::encodeGuardPatterns(), EAN13::encodeGuardPatterns(), Interleaved2of5::encodeQuietZones(), EAN8::encodeQuietZones(), EAN13::encodeQuietZones(), Code39::encodeQuietZones(), Code128::encodeQuietZones(), Codabar::encodeQuietZones(), Interleaved2of5::encodeStartStop(), Code39::encodeStartStop(), Code128::encodeStartStop(), Codabar::encodeStartStop(), Interleaved2of5::encodeSymbol(), EAN8::encodeSymbol(), EAN13::encodeSymbol(), Code39::encodeSymbol(), Codabar::encodeSymbol(), and Base128::encodeSymbol().
virtual void BaseBarcode::encodeCheckCharacter (const string * data) [protected, pure virtual]
Implemented in BaseEANUPC, Codabar, Code128, Code39, and Interleaved2of5.
virtual void BaseBarcode::encodeQuietZones () [protected, pure virtual]
Implemented in BaseEANUPC, Codabar, Code128, Code39, EAN13, EAN8, and Interleaved2of5.
virtual void BaseBarcode::encodeStartStop () [protected, pure virtual]
Implemented in BaseEANUPC, Codabar, Code128, Code39, and Interleaved2of5.
virtual void BaseBarcode::encodeSymbol (const string * data) [protected, pure virtual]
Implemented in Base128, BaseEANUPC, Codabar, Code39, EAN13, EAN8, and Interleaved2of5.
int BaseBarcode::getCheckcharModulus ()
Definition at line 47 of file BaseBarcode.cpp.
References checkcharModulus.
Referenced by Code39::encodeCheckCharacter().
int BaseBarcode::getDataLength ()
Definition at line 53 of file BaseBarcode.cpp.
References dataLength.
deque< Symbol * > BaseBarcode::getEncodedSymbols ()
Definition at line 41 of file BaseBarcode.cpp.
References encodedSymbols.
Referenced by EAN8::encodeGuardPatterns(), EAN13::encodeGuardPatterns(), EAN8::encodeQuietZones(), EAN13::encodeQuietZones(), RSBarcodeViewController::initWithType:andData:atPosition:, and main().
vector< int > BaseBarcode::getQuietzoneWidths ()
Definition at line 35 of file BaseBarcode.cpp.
References quietzoneWidths.
char * BaseBarcode::getXMLToParse (string * fileTitle) [protected]
Definition at line 144 of file BaseBarcode.cpp.
Referenced by Codabar::Codabar(), Code128::Code128(), Code39::Code39(), EAN13::EAN13(), EAN8::EAN8(), Base128::encodeSymbol(), and Interleaved2of5::Interleaved2of5().
vector< string > BaseBarcode::returnDOMValues (rapidxml::xml_node< > * node) [protected]
Definition at line 175 of file BaseBarcode.cpp.
Referenced by Base128::encodeSymbol().
void BaseBarcode::setCheckcharModulus (int modulus) [protected]
Definition at line 91 of file BaseBarcode.cpp.
References checkcharModulus.
Referenced by BaseEANUPC::BaseEANUPC(), Code128::Code128(), Code39::Code39(), and Interleaved2of5::Interleaved2of5().
void BaseBarcode::setDataLength (int length) [protected]
Definition at line 97 of file BaseBarcode.cpp.
References dataLength.
Referenced by Codabar::Codabar(), Code128::Code128(), Code39::Code39(), EAN13::EAN13(), EAN8::EAN8(), and Interleaved2of5::Interleaved2of5().
void BaseBarcode::setQuietzoneWidths (int left, int right, int upper, int lower) [protected]
Definition at line 61 of file BaseBarcode.cpp.
References quietzoneWidths.
virtual bool BaseBarcode::verifyContent (const string * content) [protected, pure virtual]
Implemented in BaseEANUPC, Codabar, Code128, Code39, and Interleaved2of5.
Referenced by verifyData().
bool BaseBarcode::verifyData (const string * data) [protected, virtual]
Definition at line 105 of file BaseBarcode.cpp.
References verifyContent(), and verifyLength().
Referenced by Codabar::Codabar(), Code128::Code128(), Code39::Code39(), EAN13::EAN13(), EAN8::EAN8(), and Interleaved2of5::Interleaved2of5().
bool BaseBarcode::verifyLength (const int length) [protected, virtual]
Definition at line 116 of file BaseBarcode.cpp.
References dataLength.
Referenced by verifyData().
Member Data Documentation
int BaseBarcode::checkcharModulus [protected]
Definition at line 58 of file BaseBarcode.h.
Referenced by getCheckcharModulus(), and setCheckcharModulus().
string BaseBarcode::completedDataString [protected]
Definition at line 60 of file BaseBarcode.h.
Referenced by Interleaved2of5::encodeCheckCharacter(), and BaseEANUPC::encodeCheckCharacter().
int BaseBarcode::dataLength [protected]
Definition at line 59 of file BaseBarcode.h.
Referenced by getDataLength(), setDataLength(), and verifyLength().
deque< Symbol* > BaseBarcode::encodedSymbols [protected]
Definition at line 57 of file BaseBarcode.h.
Referenced by addEncodedSymbol(), Code39::encodeCheckCharacter(), Code128::encodeCheckCharacter(), Interleaved2of5::encodeQuietZones(), Code39::encodeQuietZones(), Code128::encodeQuietZones(), Codabar::encodeQuietZones(), Interleaved2of5::encodeStartStop(), Code39::encodeStartStop(), Code128::encodeStartStop(), Codabar::encodeStartStop(), and getEncodedSymbols().
vector< int > BaseBarcode::quietzoneWidths [protected]
Definition at line 56 of file BaseBarcode.h.
Referenced by getQuietzoneWidths(), and setQuietzoneWidths().
The documentation for this class was generated from the following files:
/Dropbox/MSc Course/Final Project/BarcodeKit/BarcodeKit/BaseBarcode.h
/Dropbox/MSc Course/Final Project/BarcodeKit/BarcodeKit/BaseBarcode.cpp