BarcodeKit: Codabar Class Reference
Codabar Class Reference
#include <Codabar.h>
Inherits BaseBarcode.
Public Member Functions
Codabar ()
Codabar (string *data)
~Codabar ()
bool verifyContent (const string *content)
void encodeSymbol (const string *data)
void encodeStartStop ()
void encodeQuietZones ()
void encodeCheckCharacter (const string *data)
Private Member Functions
vector< int > * stringToVector (string aString)
Private Attributes
string filename
xml_document< > parsed_xml
Detailed Description
Definition at line 22 of file Codabar.h.
Constructor & Destructor Documentation
Codabar::Codabar ()
Definition at line 25 of file Codabar.cpp.
Codabar::Codabar (string * data)
Definition at line 30 of file Codabar.cpp.
References encodeCheckCharacter(), encodeQuietZones(), encodeStartStop(), encodeSymbol(), filename, BaseBarcode::getXMLToParse(), parsed_xml, BaseBarcode::setDataLength(), and BaseBarcode::verifyData().
Codabar::~Codabar ()
Definition at line 54 of file Codabar.cpp.
Member Function Documentation
void Codabar::encodeCheckCharacter (const string * data) [virtual]
Implements BaseBarcode.
Definition at line 151 of file Codabar.cpp.
Referenced by Codabar().
void Codabar::encodeQuietZones () [virtual]
Implements BaseBarcode.
Definition at line 136 of file Codabar.cpp.
References BaseBarcode::addEncodedSymbol(), BaseBarcode::createSymbol(), BaseBarcode::encodedSymbols, and parsed_xml.
Referenced by Codabar().
void Codabar::encodeStartStop () [virtual]
Implements BaseBarcode.
Definition at line 123 of file Codabar.cpp.
References BaseBarcode::addEncodedSymbol(), BaseBarcode::createSymbol(), BaseBarcode::encodedSymbols, parsed_xml, and stringToVector().
Referenced by Codabar().
void Codabar::encodeSymbol (const string * data) [virtual]
Implements BaseBarcode.
Definition at line 82 of file Codabar.cpp.
References BaseBarcode::addEncodedSymbol(), BaseBarcode::createSymbol(), kASCII, parsed_xml, and stringToVector().
Referenced by Codabar().
vector< int > * Codabar::stringToVector (string aString) [private]
Definition at line 156 of file Codabar.cpp.
Referenced by encodeStartStop(), and encodeSymbol().
bool Codabar::verifyContent (const string * content) [virtual]
Implements BaseBarcode.
Definition at line 59 of file Codabar.cpp.
Member Data Documentation
string Codabar::filename [private]
Definition at line 35 of file Codabar.h.
Referenced by Codabar().
xml_document< > Codabar::parsed_xml [private]
Definition at line 36 of file Codabar.h.
Referenced by Codabar(), encodeQuietZones(), encodeStartStop(), and encodeSymbol().
The documentation for this class was generated from the following files:
/Dropbox/MSc Course/Final Project/BarcodeKit/BarcodeKit/Codabar.h
/Dropbox/MSc Course/Final Project/BarcodeKit/BarcodeKit/Codabar.cpp