BarcodeKit: Code39 Class Reference
Code39 Class Reference
#include <Code39.h>
Inherits BaseBarcode.
Public Member Functions
Code39 (string *data)
~Code39 ()
bool verifyContent (const string *content)
void encodeSymbol (const string *data)
void encodeStartStop ()
void encodeQuietZones ()
void encodeCheckCharacter (const string *data)
Private Member Functions
vector< int > * stringToVector (string aString)
int checksumIntForChar (int aChar)
char checksumCharForInt (int anInt)
Private Attributes
string filename
xml_document< > parsed_xml
Detailed Description
Definition at line 22 of file Code39.h.
Constructor & Destructor Documentation
Code39::Code39 (string * data)
Definition at line 28 of file Code39.cpp.
References encodeCheckCharacter(), encodeQuietZones(), encodeStartStop(), encodeSymbol(), filename, BaseBarcode::getXMLToParse(), kModulus, parsed_xml, BaseBarcode::setCheckcharModulus(), BaseBarcode::setDataLength(), and BaseBarcode::verifyData().
Code39::~Code39 ()
Definition at line 53 of file Code39.cpp.
Member Function Documentation
char Code39::checksumCharForInt (int anInt) [private]
Definition at line 247 of file Code39.cpp.
References kAlphaOffset, and kNumericOffset.
Referenced by encodeCheckCharacter().
int Code39::checksumIntForChar (int aChar) [private]
Definition at line 204 of file Code39.cpp.
References kAlphaOffset, and kNumericOffset.
Referenced by encodeCheckCharacter().
void Code39::encodeCheckCharacter (const string * data) [virtual]
Implements BaseBarcode.
Definition at line 155 of file Code39.cpp.
References BaseBarcode::addEncodedSymbol(), checksumCharForInt(), checksumIntForChar(), BaseBarcode::createSymbol(), BaseBarcode::encodedSymbols, BaseBarcode::getCheckcharModulus(), kASCII, parsed_xml, and stringToVector().
Referenced by Code39().
void Code39::encodeQuietZones () [virtual]
Implements BaseBarcode.
Definition at line 139 of file Code39.cpp.
References BaseBarcode::addEncodedSymbol(), BaseBarcode::createSymbol(), BaseBarcode::encodedSymbols, and parsed_xml.
Referenced by Code39().
void Code39::encodeStartStop () [virtual]
Implements BaseBarcode.
Definition at line 125 of file Code39.cpp.
References BaseBarcode::addEncodedSymbol(), BaseBarcode::createSymbol(), BaseBarcode::encodedSymbols, parsed_xml, and stringToVector().
Referenced by Code39().
void Code39::encodeSymbol (const string * data) [virtual]
Implements BaseBarcode.
Definition at line 83 of file Code39.cpp.
References BaseBarcode::addEncodedSymbol(), BaseBarcode::createSymbol(), kASCII, parsed_xml, and stringToVector().
Referenced by Code39().
vector< int > * Code39::stringToVector (string aString) [private]
Definition at line 191 of file Code39.cpp.
Referenced by encodeCheckCharacter(), encodeStartStop(), and encodeSymbol().
bool Code39::verifyContent (const string * content) [virtual]
Implements BaseBarcode.
Definition at line 59 of file Code39.cpp.
Member Data Documentation
string Code39::filename [private]
Definition at line 34 of file Code39.h.
Referenced by Code39().
xml_document< > Code39::parsed_xml [private]
Definition at line 35 of file Code39.h.
Referenced by Code39(), encodeCheckCharacter(), encodeQuietZones(), encodeStartStop(), and encodeSymbol().
The documentation for this class was generated from the following files:
/Dropbox/MSc Course/Final Project/BarcodeKit/BarcodeKit/Code39.h
/Dropbox/MSc Course/Final Project/BarcodeKit/BarcodeKit/Code39.cpp