BarcodeKit: EAN8 Class Reference
EAN8 Class Reference
#include <EAN8.h>
Inherits BaseEANUPC, and IGuardPatterns.
Public Member Functions
EAN8 (string *data)
~EAN8 ()
void encodeSymbol (const string *data)
void encodeQuietZones ()
void encodeGuardPatterns ()
void setGuardPatterns (string left, string centre, string right)
vector< string > getGuardPatterns ()
vector< int > * stringToVector (string aString)
Public Attributes
string filename
string parityFilename
vector< string > guardPatterns
xml_document< > parsed_xml
Detailed Description
Definition at line 23 of file EAN8.h.
Constructor & Destructor Documentation
EAN8::EAN8 (string * data)
Definition at line 24 of file EAN8.cpp.
References BaseEANUPC::encodeCheckCharacter(), encodeQuietZones(), filename, BaseBarcode::getXMLToParse(), parsed_xml, BaseBarcode::setDataLength(), setGuardPatterns(), and BaseBarcode::verifyData().
EAN8::~EAN8 ()
Definition at line 53 of file EAN8.cpp.
Member Function Documentation
void EAN8::encodeGuardPatterns () [virtual]
Implements BaseEANUPC.
Definition at line 124 of file EAN8.cpp.
References BaseBarcode::addEncodedSymbol(), BaseBarcode::createSymbol(), BaseBarcode::getEncodedSymbols(), getGuardPatterns(), and stringToVector().
Referenced by encodeSymbol().
void EAN8::encodeQuietZones () [virtual]
Reimplemented from BaseEANUPC.
Definition at line 105 of file EAN8.cpp.
References BaseBarcode::addEncodedSymbol(), BaseBarcode::createSymbol(), BaseBarcode::getEncodedSymbols(), and parsed_xml.
Referenced by EAN8().
void EAN8::encodeSymbol (const string * data) [virtual]
Reimplemented from BaseEANUPC.
Definition at line 59 of file EAN8.cpp.
References BaseBarcode::addEncodedSymbol(), BaseBarcode::createSymbol(), encodeGuardPatterns(), kASCII, parsed_xml, and stringToVector().
vector< string > EAN8::getGuardPatterns () [virtual]
Implements BaseEANUPC.
Definition at line 160 of file EAN8.cpp.
References guardPatterns.
Referenced by encodeGuardPatterns().
void EAN8::setGuardPatterns (string left, string centre, string right) [virtual]
Implements BaseEANUPC.
Definition at line 152 of file EAN8.cpp.
References guardPatterns.
Referenced by EAN8().
vector< int > * EAN8::stringToVector (string aString)
Definition at line 166 of file EAN8.cpp.
Referenced by encodeGuardPatterns(), and encodeSymbol().
Member Data Documentation
string EAN8::filename
Definition at line 35 of file EAN8.h.
Referenced by EAN8().
vector< string > EAN8::guardPatterns
Definition at line 37 of file EAN8.h.
Referenced by getGuardPatterns(), and setGuardPatterns().
string EAN8::parityFilename
Definition at line 36 of file EAN8.h.
xml_document< > EAN8::parsed_xml
Definition at line 38 of file EAN8.h.
Referenced by EAN8(), encodeQuietZones(), and encodeSymbol().
The documentation for this class was generated from the following files:
/Dropbox/MSc Course/Final Project/BarcodeKit/BarcodeKit/EAN8.h
/Dropbox/MSc Course/Final Project/BarcodeKit/BarcodeKit/EAN8.cpp