BarcodeKit: EAN13 Class Reference
EAN13 Class Reference
#include <EAN13.h>
Inherits BaseEANUPC, and IGuardPatterns.
Public Member Functions
EAN13 (string *data)
~EAN13 ()
void encodeSymbol (const string *data)
void encodeQuietZones ()
void encodeGuardPatterns ()
void setGuardPatterns (string left, string centre, string right)
vector< string > getGuardPatterns ()
vector< int > * stringToVector (string aString)
Public Attributes
string filename
string parityFilename
vector< string > guardPatterns
xml_document< > parsed_xml
xml_document< > parity_xml
Detailed Description
Definition at line 23 of file EAN13.h.
Constructor & Destructor Documentation
EAN13::EAN13 (string * data)
Definition at line 24 of file EAN13.cpp.
References BaseEANUPC::encodeCheckCharacter(), encodeQuietZones(), filename, BaseBarcode::getXMLToParse(), parity_xml, parityFilename, parsed_xml, BaseBarcode::setDataLength(), setGuardPatterns(), and BaseBarcode::verifyData().
EAN13::~EAN13 ()
Definition at line 55 of file EAN13.cpp.
Member Function Documentation
void EAN13::encodeGuardPatterns () [virtual]
Implements BaseEANUPC.
Definition at line 132 of file EAN13.cpp.
References BaseBarcode::addEncodedSymbol(), BaseBarcode::createSymbol(), BaseBarcode::getEncodedSymbols(), getGuardPatterns(), and stringToVector().
Referenced by encodeSymbol().
void EAN13::encodeQuietZones () [virtual]
Reimplemented from BaseEANUPC.
Definition at line 113 of file EAN13.cpp.
References BaseBarcode::addEncodedSymbol(), BaseBarcode::createSymbol(), BaseBarcode::getEncodedSymbols(), and parsed_xml.
Referenced by EAN13().
void EAN13::encodeSymbol (const string * data) [virtual]
Reimplemented from BaseEANUPC.
Definition at line 61 of file EAN13.cpp.
References BaseBarcode::addEncodedSymbol(), BaseBarcode::createSymbol(), encodeGuardPatterns(), kASCII, parity_xml, parsed_xml, and stringToVector().
vector< string > EAN13::getGuardPatterns () [virtual]
Implements BaseEANUPC.
Definition at line 168 of file EAN13.cpp.
References guardPatterns.
Referenced by encodeGuardPatterns().
void EAN13::setGuardPatterns (string left, string centre, string right) [virtual]
Implements BaseEANUPC.
Definition at line 160 of file EAN13.cpp.
References guardPatterns.
Referenced by EAN13().
vector< int > * EAN13::stringToVector (string aString)
Definition at line 174 of file EAN13.cpp.
Referenced by encodeGuardPatterns(), and encodeSymbol().
Member Data Documentation
string EAN13::filename
Definition at line 35 of file EAN13.h.
Referenced by EAN13().
vector< string > EAN13::guardPatterns
Definition at line 37 of file EAN13.h.
Referenced by getGuardPatterns(), and setGuardPatterns().
xml_document< > EAN13::parity_xml
Definition at line 39 of file EAN13.h.
Referenced by EAN13(), and encodeSymbol().
string EAN13::parityFilename
Definition at line 36 of file EAN13.h.
Referenced by EAN13().
xml_document< > EAN13::parsed_xml
Definition at line 38 of file EAN13.h.
Referenced by EAN13(), encodeQuietZones(), and encodeSymbol().
The documentation for this class was generated from the following files:
/Dropbox/MSc Course/Final Project/BarcodeKit/BarcodeKit/EAN13.h
/Dropbox/MSc Course/Final Project/BarcodeKit/BarcodeKit/EAN13.cpp