BarcodeKit: Base128 Class Reference
Base128 Class Reference
#include <Base128.h>
Inherits BaseBarcode.
Inherited by Code128.
Protected Member Functions
Base128 ()
~Base128 ()
virtual void encodeSymbol (const string *data)
virtual int returnCheckCharASCII ()=0
Protected Attributes
vector< int > * checkCharList
Detailed Description
Definition at line 22 of file Base128.h.
Constructor & Destructor Documentation
Base128::Base128 () [protected]
Definition at line 30 of file Base128.cpp.
Base128::~Base128 () [protected]
Definition at line 36 of file Base128.cpp.
Member Function Documentation
void Base128::encodeSymbol (const string * data) [protected, virtual]
Implements BaseBarcode.
Definition at line 44 of file Base128.cpp.
References BaseBarcode::addEncodedSymbol(), checkCharList, BaseBarcode::createSymbol(), BaseBarcode::getXMLToParse(), kASCII, kOffsetASCII, kSetA, kSetB, kSetC, and BaseBarcode::returnDOMValues().
Referenced by Code128::Code128().
virtual int Base128::returnCheckCharASCII () [protected, pure virtual]
Implemented in Code128.
Member Data Documentation
vector< int >* Base128::checkCharList [protected]
Definition at line 30 of file Base128.h.
Referenced by Code128::Code128(), Code128::encodeCheckCharacter(), encodeSymbol(), and Code128::~Code128().
The documentation for this class was generated from the following files:
/Dropbox/MSc Course/Final Project/BarcodeKit/BarcodeKit/Base128.h
/Dropbox/MSc Course/Final Project/BarcodeKit/BarcodeKit/Base128.cpp