BarcodeKit: /Dropbox/MSc Course/Final Project/BarcodeKit/BarcodeKit/main.cpp File Reference
/Dropbox/MSc Course/Final Project/BarcodeKit/BarcodeKit/main.cpp File Reference
#include <iostream>
#include <vector>
#include <deque>
#include <fstream>
#include <sstream>
#include <string>
#include "Symbol.h"
#include "rapidxml.hpp"
#include "Codabar.h"
#include "Code39.h"
#include "Interleaved2of5.h"
#include "EAN13.h"
#include "EAN8.h"
#include "UPCA.h"
#include "UPCE.h"
#include "Code128.h"
Functions
Symbol * createSymbol (int st, int ic, int le, int fp, vector< int > *aVector)
void testSymbol (Symbol *testSymbol)
char * getXMLToParse (string *fileTitle)
void testDOM (xml_node< > *node)
vector< string > returnDOMValues (xml_node< > *node)
int main (int argc, const char *argv[])
Function Documentation
Symbol * createSymbol (int st, int ic, int le, int fp, vector< int > * aVector)
Definition at line 58 of file main.cpp.
References Symbol::setEncodedData(), Symbol::setForcedPosition(), Symbol::setIntercharGap(), Symbol::setLeadingElement(), and Symbol::setSymbolType().
Referenced by UPCE::encodeGuardPatterns(), UPCA::encodeGuardPatterns(), UPCE::encodeQuietZones(), UPCA::encodeQuietZones(), UPCE::encodeSymbol(), and UPCA::encodeSymbol().
char * getXMLToParse (string * fileTitle)
Definition at line 85 of file main.cpp.
Referenced by UPCA::UPCA(), and UPCE::UPCE().
int main (int argc, const char * argv[])
Definition at line 40 of file main.cpp.
References BaseBarcode::getEncodedSymbols().
vector< string > returnDOMValues (xml_node< > * node)
Definition at line 134 of file main.cpp.
void testDOM (xml_node< > * node)
Definition at line 115 of file main.cpp.
void testSymbol (Symbol * testSymbol)
Definition at line 69 of file main.cpp.
References Symbol::getEncodedData(), Symbol::getForcePostion(), Symbol::getIntercharGap(), Symbol::getLeadingElement(), and Symbol::getSymbolType().